### ISSUE TITLE
-0.012345 in json returns a positive json_number

### ISSUE THREAD

**Issue by lumonix** [vurtun/mmx#20]
`{
    "shader": {
        "name": "Voronoi",
        "category": "Patterns",
        "help": "Generates Voronoi cells",
        "includes": [
            "/shaders/include/header.include",
        ],
        "stages": [
            "VERT_SHADER",
            "FRAG_SHADER"
        ],
        "parameters": [
            {"name": "scale", "value": 1.5000, "min": 0.1, "max": 5.0, "step": 0.2},
            {"name": "color", "value": [0.7546, 0.500000, -0.012345, 1.0000]}
        ]
    }
}`

The value '-0.012345' will return a positive json_number instead of negative.

**Comment by lumonix** [comment]
Should have mentioned, this is with msvc compiler (2017 on Win10).
    i = json_stoi(&nums[INT]);
.....
    *num = (i + ((i < 0) ? -f : f)) * p;

probably fairly easy to fix by having json_stoi return 'neg' state instead. But I'm not too familiar with the code yet.

**Comment by vurtun** [comment]
Hey @lumonix 
thanks for the issue hopefully it is fixed now.

**Comment by lumonix** [comment]
@vurtun yes fixed. Thanks!
