### ISSUE TITLE
lexer_read gives wrong token data for '/'

### ISSUE THREAD

**Issue by ddengster** [vurtun/mmx#21]
So lexer_read goes through the 'lexer_read_name' path when encountering a slash. This is likely incorrect, for the use case below; I was expecting punctuation instead. Check line 1315 of lexer.h.

For reference, I'm trying to parse code like this:
inline Vector2 operator/(float scalar) const;

**Comment by vurtun** [comment]
Hey @ddengster,
thanks for the issue. Should hopefully be fixed now.
